[project]
name = "python-fit-tool"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "geopy>=2.4.1",
    "gpxpy>=1.6.2",
    "inflection>=0.5.1",
    "jinja2>=3.1.6",
    "openpyxl>=3.1.5",
    "pyside6>=6.9.0",
]
